name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.4.x', '2.5.x', '2.6.x']
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install Bundler
      run: gem install bundler
    - name: Install dependencies
      run: |
        sudo apt-get install -y libsqlite3-dev
        bundle install -j4
    - name: Setup the dummy app
      run: (cd test/dummy && bin/rake db:create db:migrate)
    - name: Run test
      run: bin/test
